## HW 2.1

**Ex.1**

Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;<br>
       *Ответ: нельзя найти ни произведение АВ, ни ВА.*<br><br>
       
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;<br>
   *Ответ: АВ = С ($2\times3$)*<br><br>
   
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;<br>
   *Ответ: AB = C ($8\times8$);*<br>
   *BA = D ($3\times3$).*<br><br>
   
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.<br>
   *Ответ: АВ = С ($4\times4$);<br>
   ВА = D ($4\times4$).*
   

**Ex.2**

Найти сумму и произведение матриц

 $A + B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ =
 $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

 $A \times B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \times \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} =
 \begin{pmatrix}
(4+0) & (-1-10)\\ 
(12+0) & (-3+0)
\end{pmatrix}  =
 \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [84]:
import numpy as np

In [85]:
A = np.array([[1,-2], [3,0]])
B = np.array([[4,-1], [0,5]])

In [86]:
A+B

array([[ 5, -3],
       [ 3,  5]])

In [87]:
A@B

array([[  4, -11],
       [ 12,  -3]])

**Ex.3**

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C = 3 \times \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\times \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\times \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \\
= \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \\
= \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}
$

In [88]:
A = np.array([[1,7], [3,-6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1,1]])

3*A-2*B+4*C

**Ex.4**

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^T = \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}$

$AA^T = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
(16+1) & (20-2) & (8+3) \\
(20-2) & (25+4) & (10-6) \\
(8+3) & (10-6) & (4+9)
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}
$

$A^TA = \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} \times
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = 
\begin{pmatrix}
(16+25+4) & (4-10+6)\\
(4-10+6) & (1+4+9)
\end{pmatrix}=
\begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}
$

In [89]:
A = np.array([[4,1],[5,-2],[2,3]])

In [90]:
AT = A.T

In [91]:
A.dot(AT)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [92]:
AT.dot(A)

array([[45,  0],
       [ 0, 14]])

**Ex.5***

Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [93]:
def matrix_multiplication(a: list, b: list):
  
    try:
        for i in range(len(a)):
            if len(a[i]) != len(a[0]):
                print('First matrix initialized improperly.')
                return
        for i in range(len(b)):
            if len(b[i]) != len(b[0]):
                print('Second matrix initialized improperly.')
                return
        c = []
        d = []

        rowsa = len(a)
        columnsa = len(b)
        columnsb  = len(b[0])
        if rowsa != columnsb:
            print('Inappropriate dimensions of the matrices')
            return

        for x in range(rowsa): 
            for z in range(columnsb):
                num = 0
                for y in range(columnsa): 
                    num += a[x][y]*b[y][z]
                d.append(num)
            c.append(d)
            d = []
        return c            
    except TypeError:
        print('Initialize matrix as list of lists.')
    else:
        print('Something went wrong :(')

In [94]:
A = [[1,-2], [3,0]]
B = [[4,-1], [0,5]]
matrix_multiplication(A, B)

[[4, -11], [12, -3]]

## HW 2.2

**Ex.1**

Вычислить определитель:

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = (sinx)^2 + (cosx)^2 = 0.5(1-cos2x) + 0.5(1+cos2x) = 0.5\cdot2 = 1$

In [95]:
x = 21
A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
np.linalg.det(A)

1.0

б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\cdot \begin{vmatrix}5 & 1\\ 0 & 9 \end{vmatrix} - 0 + 0 = 4\cdot(5\cdot9 - 0\cdot 1) = 4\cdot45 = 180$

In [96]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(B)

180.0

  в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 7\cdot\begin{vmatrix}2 & 3\\ 5 & 6\end{vmatrix} - 8\cdot\begin{vmatrix}1 & 3\\ 4 & 6\end{vmatrix} + 9\cdot
\begin{vmatrix}1 & 2\\ 4 & 5\end{vmatrix} = 7\cdot(12 - 15) - 8\cdot(6-12) + 9\cdot(5 -  8)=-21 + 48-27 =0$

In [97]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(C)

0.0

**Ex.2**

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;<br>
 Если матрицу можно умножить саму на себя, значит она квадратная. Для двух квадратных матриц одинакового размера справедливо следующее равенство:
$$det(AB)=detA\cdot detB.$$
Значит <br>
$det(A^2) = detA\cdot detA = detA^2 = 4^2 = 16$

   б) $det(A^{T}) = 4$<br>
  Определитель транспонированной матрицы равен определителю исходной матрицы

  в) $det(2A) = 2^ndetA=2^n4=2^{n+2}$,<br>
  где n - размер матрицы (кол-во строк или столбцов).<br>
  При домножении строки/столбца матрицы на число, определитель также домножается на это число. Т.е. если мы домножаем n строк на 2, определитель мы должны домножить на $2^n$.

**Ex.3**

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Вторая строка линейно зависима от первой. Значит определитель равен нулю.<br><br>
Прибавим ко второй строке первую, домноженную на 2:<br>
$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$ = $\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}$<br>
Вторая строка обращается в ноль. Определитель матрицы, содержащей нулевую строку, равен нулю. Значит матрица вырожденная.

**Ex. 4**

Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 1\\ 
1 & 2 & 3\\ 
0 & 1 & 2
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2\\ 
0 & 1 & 2
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 3\\ 
0 & 1 & 2
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 1\\ 
0 & 1 & 1
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 1
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 0\\ 
0 & 1 & 0
\end{pmatrix}=
\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix}$<br>
<u>Ранг матрицы: 2</u>

In [98]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}=
\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 2 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}=
\begin{pmatrix}
0 & 0 & 0 & 0\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 2 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}=
\begin{pmatrix} 
0 & 0 & 2 & 2\\ 
0 & 0 & 2 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}=
\begin{pmatrix} 
0 & 0 & 0 & 1\\ 
0 & 0 & 2 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}=
\begin{pmatrix} 
0 & 0 & 0 & 1\\ 
0 & 0 & 2 & 1\\ 
0 & 3 & 5 & 6
\end{pmatrix}=
\begin{pmatrix}
0 & 0 & 1\\ 
0 & 2 & 1\\ 
3 & 5 & 6
\end{pmatrix}$<br>
<u>Ранг матрицы: 3</u>

In [99]:
A = np.array([[0, 0, 2, 1], [0, 0, 2 , 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(A)

3