## HW5

### Ex.1

1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


In [19]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [20]:
A = np.array([[1,2,0],
              [0,0,5],
             [3,-4,2],
             [1,6,5],
             [0,1,0]])

U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [21]:
print(f'U matrix: \n', U)
print(f'D matrix: \n', D)
print(f'V matrix: \n', V)

U matrix: 
 [[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
D matrix: 
 [[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
V matrix: 
 [[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [22]:
print(f'Checking: \n', np.dot((np.dot(U,D)), V.T))

Checking: 
 [[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


### Ex.2

2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    


In [24]:
A_E = D[0,0]
A_E

8.824868854820444

    б) норму Фробениуса.

In [30]:
A_F = 0
for i in range(len(s)):
    A_F += s[i]**2
A_F

122.00000000000003